#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WineHangouts.Resource", IsApplication=true)]

namespace WineHangouts
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int camera = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cell_shape = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Close = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int delete = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dpreplacer = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int edit = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Gallery = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int heart_empty = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int heart_full = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_white = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_white1 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon2 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int placeholder = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int placeholder_11 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int placeholder_bottiglia_lista = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int placeholder_re = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ratingstars = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int regione_lombardia = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Reimage = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int respon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int sfondo_blog = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int sfondo_cantine = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int sfondo_catalogo_vini = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int sfondo_mierecensioni = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int sfondo_nuoverecensioni = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int sfondo_promozioni = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int sfondo_regioni = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int sfondo_selezioni = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int sfondo_topvini = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int sfondo_wineprofile = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int star = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int star_empty = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Tes = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int user = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int wine1 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int wine6 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int wine7 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int wine_review = 2130837543;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060053
			public const int AvgRating = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int Date = 2131099732;
			
			// aapt resource value: 0x7f06004d
			public const int MyTasting = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int SkuName = 2131099726;
			
			// aapt resource value: 0x7f060055
			public const int TastingNotes = 2131099733;
			
			// aapt resource value: 0x7f060052
			public const int Vintage = 2131099730;
			
			// aapt resource value: 0x7f06001f
			public const int avgrating = 2131099679;
			
			// aapt resource value: 0x7f06003b
			public const int btnBottom = 2131099707;
			
			// aapt resource value: 0x7f06005c
			public const int btnCamera = 2131099740;
			
			// aapt resource value: 0x7f060057
			public const int btnChangePropic = 2131099735;
			
			// aapt resource value: 0x7f06005d
			public const int btnGallery = 2131099741;
			
			// aapt resource value: 0x7f060042
			public const int btnLoginLL = 2131099714;
			
			// aapt resource value: 0x7f06003a
			public const int btnMiddle = 2131099706;
			
			// aapt resource value: 0x7f060035
			public const int btnSubmitReview = 2131099701;
			
			// aapt resource value: 0x7f060039
			public const int btnTop = 2131099705;
			
			// aapt resource value: 0x7f060017
			public const int button1 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int button2 = 2131099672;
			
			// aapt resource value: 0x7f06002e
			public const int close = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int edittext = 2131099693;
			
			// aapt resource value: 0x7f060036
			public const int fragmentContainer = 2131099702;
			
			// aapt resource value: 0x7f060043
			public const int gridview = 2131099715;
			
			// aapt resource value: 0x7f06004c
			public const int gridviewfav = 2131099724;
			
			// aapt resource value: 0x7f06000d
			public const int imageButton2 = 2131099661;
			
			// aapt resource value: 0x7f06004f
			public const int imageButton3 = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int imageButton4 = 2131099728;
			
			// aapt resource value: 0x7f06005b
			public const int imageView1 = 2131099739;
			
			// aapt resource value: 0x7f060005
			public const int imgHeart = 2131099653;
			
			// aapt resource value: 0x7f060047
			public const int imgHeartfav = 2131099719;
			
			// aapt resource value: 0x7f060004
			public const int imgWine = 2131099652;
			
			// aapt resource value: 0x7f06001d
			public const int imgWine12 = 2131099677;
			
			// aapt resource value: 0x7f060046
			public const int imgWinefav = 2131099718;
			
			// aapt resource value: 0x7f06003f
			public const int lblPassword = 2131099711;
			
			// aapt resource value: 0x7f06003c
			public const int lblUsername = 2131099708;
			
			// aapt resource value: 0x7f060041
			public const int linearLayoutBtns = 2131099713;
			
			// aapt resource value: 0x7f06005e
			public const int listView1 = 2131099742;
			
			// aapt resource value: 0x7f06002c
			public const int listView2 = 2131099692;
			
			// aapt resource value: 0x7f060045
			public const int placeholdefavr = 2131099717;
			
			// aapt resource value: 0x7f060003
			public const int placeholder = 2131099651;
			
			// aapt resource value: 0x7f06001c
			public const int placeholder1 = 2131099676;
			
			// aapt resource value: 0x7f060056
			public const int propicview = 2131099734;
			
			// aapt resource value: 0x7f060033
			public const int rating = 2131099699;
			
			// aapt resource value: 0x7f060024
			public const int ratingInput = 2131099684;
			
			// aapt resource value: 0x7f060032
			public const int ratingimage = 2131099698;
			
			// aapt resource value: 0x7f060002
			public const int relative = 2131099650;
			
			// aapt resource value: 0x7f060030
			public const int relativeLayout1 = 2131099696;
			
			// aapt resource value: 0x7f060058
			public const int relativeLayout2 = 2131099736;
			
			// aapt resource value: 0x7f060044
			public const int relativefav = 2131099716;
			
			// aapt resource value: 0x7f060009
			public const int rtbProductRating = 2131099657;
			
			// aapt resource value: 0x7f06004a
			public const int rtbProductRatingfav = 2131099722;
			
			// aapt resource value: 0x7f06005a
			public const int save = 2131099738;
			
			// aapt resource value: 0x7f060000
			public const int tableLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int tableLayout3 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int tableLayout4 = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int tableRow1 = 2131099649;
			
			// aapt resource value: 0x7f060016
			public const int tableRow2 = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int tableRow3 = 2131099673;
			
			// aapt resource value: 0x7f060061
			public const int tableRow4 = 2131099745;
			
			// aapt resource value: 0x7f06001b
			public const int tableRow5 = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int tableRow6 = 2131099680;
			
			// aapt resource value: 0x7f060022
			public const int tableRow7 = 2131099682;
			
			// aapt resource value: 0x7f06001e
			public const int tableRow78 = 2131099678;
			
			// aapt resource value: 0x7f060025
			public const int tableRow8 = 2131099685;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow88 = 2131099660;
			
			// aapt resource value: 0x7f060051
			public const int tableRow89 = 2131099729;
			
			// aapt resource value: 0x7f06002b
			public const int tableRow9 = 2131099691;
			
			// aapt resource value: 0x7f060011
			public const int tableRow90 = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int tableRow91 = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int tableRow95 = 2131099664;
			
			// aapt resource value: 0x7f06002f
			public const int textView1 = 2131099695;
			
			// aapt resource value: 0x7f060015
			public const int textView10 = 2131099669;
			
			// aapt resource value: 0x7f060037
			public const int textView12 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int textView13 = 2131099704;
			
			// aapt resource value: 0x7f060060
			public const int textView14 = 2131099744;
			
			// aapt resource value: 0x7f060021
			public const int textView19 = 2131099681;
			
			// aapt resource value: 0x7f060031
			public const int textView2 = 2131099697;
			
			// aapt resource value: 0x7f060023
			public const int textView20 = 2131099683;
			
			// aapt resource value: 0x7f060026
			public const int textView33 = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int textView36 = 2131099688;
			
			// aapt resource value: 0x7f06000f
			public const int textView64 = 2131099663;
			
			// aapt resource value: 0x7f06005f
			public const int textView65 = 2131099743;
			
			// aapt resource value: 0x7f060014
			public const int textView66 = 2131099668;
			
			// aapt resource value: 0x7f060012
			public const int textView67 = 2131099666;
			
			// aapt resource value: 0x7f06002a
			public const int textView99 = 2131099690;
			
			// aapt resource value: 0x7f06003d
			public const int titleLogin = 2131099709;
			
			// aapt resource value: 0x7f060007
			public const int topDivider = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int txtName = 2131099654;
			
			// aapt resource value: 0x7f060048
			public const int txtNamefav = 2131099720;
			
			// aapt resource value: 0x7f060040
			public const int txtPassword = 2131099712;
			
			// aapt resource value: 0x7f06000a
			public const int txtPrice = 2131099658;
			
			// aapt resource value: 0x7f06004b
			public const int txtPricefav = 2131099723;
			
			// aapt resource value: 0x7f060029
			public const int txtProducer = 2131099689;
			
			// aapt resource value: 0x7f060059
			public const int txtProfileName = 2131099737;
			
			// aapt resource value: 0x7f060034
			public const int txtReviewComments = 2131099700;
			
			// aapt resource value: 0x7f06003e
			public const int txtUsername = 2131099710;
			
			// aapt resource value: 0x7f060008
			public const int txtVintage = 2131099656;
			
			// aapt resource value: 0x7f060049
			public const int txtVintagefav = 2131099721;
			
			// aapt resource value: 0x7f060027
			public const int txtWineDescription = 2131099687;
			
			// aapt resource value: 0x7f06001a
			public const int txtWineName = 2131099674;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int border = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int cell = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CommentsCell = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DeleteReviewPop = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int detailedView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Dummy = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int EditReviewPopup = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Fragment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LocationLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int login = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MyFavorite = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MyFavoriteGridView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int MyTasting = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int MyTastingView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Profile = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ProfilePickLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Tasting = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int TastingListview = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int WinePropertiesCell = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int openCamera = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int openGallery = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int rtbProductRating = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
